minecraft_questions = [
    {"question": "You can use a piston to push obsidian blocks.", "answer": "False"},
    {"question": "A conduit only works underwater when surrounded by prismarine blocks.", "answer": "True"},
    {"question": "You can craft a nether star using blaze powder and diamonds.", "answer": "False"},
    {"question": "A fox can hold a totem of undying and use it if it takes fatal damage.", "answer": "True"},
    {"question": "You can use a compass to locate your spawn point in the Nether.", "answer": "False"},
    {"question": "Soul speed enchantment only works on soul sand and soul soil.", "answer": "True"},
    {"question": "You can place water in the Nether using a cauldron.", "answer": "True"},
    {"question": "All types of wood planks have the same burn time in a furnace.", "answer": "True"},
    {"question": "You can enchant a shield using an enchanting table.", "answer": "False"},
    {"question": "A villager with a profession will lose it if their workstation is destroyed.", "answer": "True"},
    {"question": "Turtles can be bred using seagrass.", "answer": "True"},
    {"question": "The light level required to grow crops is lower than that required to prevent mobs from spawning.", "answer": "False"},
    {"question": "The only way to obtain a dragon egg is by defeating the Ender Dragon.", "answer": "True"},
    {"question": "Potion of Night Vision can be brewed using a golden carrot.", "answer": "True"},
    {"question": "You can dye leather armor by combining it with dye in a crafting table.", "answer": "True"},
    {"question": "Snow golems leave a trail of snow in every biome.", "answer": "False"},
    {"question": "A hoe is the fastest tool to break hay bales.", "answer": "False"},
    {"question": "Zombified piglins will attack you even if you look at them.", "answer": "False"},
    {"question": "You can create infinite lava sources in Minecraft like you can with water.", "answer": "False"},
    {"question": "Netherite gear does not burn in lava.", "answer": "True"},
    {"question": "You can use a grindstone to remove curse enchantments.", "answer": "False"},
    {"question": "Striders move faster in lava when ridden without a saddle.", "answer": "False"},
    {"question": "The warden can be distracted by throwing projectiles.", "answer": "True"},
    {"question": "You can use an axe to strip warped and crimson stems.", "answer": "True"},
    {"question": "End crystals can be used to respawn the Ender Dragon.", "answer": "True"}
]
